/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projdemo.Pages;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author OMA
 */
public class Info_Page extends javax.swing.JFrame {

    /**
     * Creates new form Info_Page
     */
    public Info_Page() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        Bilal_Pic = new javax.swing.JLabel();
        Oma_Pic = new javax.swing.JLabel();
        Omer_Pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projdemo/gzonebig.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 309, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 27, 184, 44));

        jLabel33.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 0, 153));
        jLabel33.setText("The Team");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 250, -1));

        Bilal_Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projdemo/icon/Bilal.jpeg"))); // NOI18N
        getContentPane().add(Bilal_Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 220, -1));

        Oma_Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projdemo/icon/Omair.jpeg"))); // NOI18N
        getContentPane().add(Oma_Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 220, 230));

        Omer_Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projdemo/icon/Omer.jpeg"))); // NOI18N
        getContentPane().add(Omer_Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 220, 230));

        jLabel2.setFont(new java.awt.Font("Elephant", 3, 16)); // NOI18N
        jLabel2.setText("Syed Bilal Mohsin ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 190, 40));

        jLabel3.setFont(new java.awt.Font("Elephant", 3, 16)); // NOI18N
        jLabel3.setText("Omair Mairaj Ansari ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 220, 40));

        jLabel4.setFont(new java.awt.Font("Elephant", 3, 16)); // NOI18N
        jLabel4.setText("M. Omer Shakeel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 160, 40));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("bilalmohsin123@icloud.com");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, 230, 20));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ERP: 17871");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 120, 20));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("BSCS-5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 70, 20));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ERP: 17849");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 120, 20));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ERP: 17902");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 100, 20));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("BSCS-5");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 70, 20));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("BSCS-5");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 70, 20));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("omairmairaj@gmail.com");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 200, 20));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("m.omer.17902@khi.iba.edu.pk");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 260, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Login_Page.e.equals("Admin")){
            HomeAdmin ob = new HomeAdmin();
            ob.setVisible(true);
        } else if(Login_Page.e.equals("User")){
            HomeUser ob = new HomeUser(Login_Page.id);
            ob.setVisible(true);
        } else if(Login_Page.e.equals("Visitor")){
            HomeVisitor ob = new HomeVisitor();
            ob.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bilal_Pic;
    private javax.swing.JLabel Oma_Pic;
    private javax.swing.JLabel Omer_Pic;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
